

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class frequencyView : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the frequencyView entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public frequencyView()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public frequencyView(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.frequencyView> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.frequencyView.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void frequencyView_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void frequencyView_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string SchoolName
        {
            get
            {
                return global::LightSwitchApplication.frequencyView.DetailsClass.GetValue(this, global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.SchoolName);
            }
            set
            {
                global::LightSwitchApplication.frequencyView.DetailsClass.SetValue(this, global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.SchoolName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SchoolName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SchoolName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void SchoolName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int frequencyNum
        {
            get
            {
                return global::LightSwitchApplication.frequencyView.DetailsClass.GetValue(this, global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.frequencyNum);
            }
            set
            {
                global::LightSwitchApplication.frequencyView.DetailsClass.SetValue(this, global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.frequencyNum, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void frequencyNum_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void frequencyNum_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void frequencyNum_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.frequencyView,
                global::LightSwitchApplication.frequencyView.DetailsClass,
                global::LightSwitchApplication.frequencyView.DetailsClass.IImplementation,
                global::LightSwitchApplication.frequencyView.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.SchoolName;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass>.Entry
                __frequencyViewEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass>.Entry(
                    global::LightSwitchApplication.frequencyView.DetailsClass.__frequencyView_CreateNew,
                    global::LightSwitchApplication.frequencyView.DetailsClass.__frequencyView_Created,
                    global::LightSwitchApplication.frequencyView.DetailsClass.__frequencyView_AllowSaveWithErrors);
            private static global::LightSwitchApplication.frequencyView __frequencyView_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.frequencyView> es)
            {
                return new global::LightSwitchApplication.frequencyView(es);
            }
            private static void __frequencyView_Created(global::LightSwitchApplication.frequencyView e)
            {
                e.frequencyView_Created();
            }
            private static bool __frequencyView_AllowSaveWithErrors(global::LightSwitchApplication.frequencyView e)
            {
                bool result = false;
                e.frequencyView_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.frequencyView.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, string> SchoolName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.SchoolName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, int> frequencyNum
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties.frequencyNum) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, int>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new string SchoolName { get; set; }
                new int frequencyNum { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, string>.Entry
                    SchoolName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, string>.Entry(
                        "SchoolName",
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._SchoolName_Stub,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._SchoolName_ComputeIsReadOnly,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._SchoolName_Validate,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._SchoolName_GetImplementationValue,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._SchoolName_SetImplementationValue,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._SchoolName_OnValueChanged);
                private static void _SchoolName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.frequencyView.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, string>.Data> c, global::LightSwitchApplication.frequencyView.DetailsClass d, object sf)
                {
                    c(d, ref d._SchoolName, sf);
                }
                private static bool _SchoolName_ComputeIsReadOnly(global::LightSwitchApplication.frequencyView e)
                {
                    bool result = false;
                    e.SchoolName_IsReadOnly(ref result);
                    return result;
                }
                private static void _SchoolName_Validate(global::LightSwitchApplication.frequencyView e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.SchoolName_Validate(r);
                }
                private static string _SchoolName_GetImplementationValue(global::LightSwitchApplication.frequencyView.DetailsClass d)
                {
                    return d.ImplementationEntity.SchoolName;
                }
                private static void _SchoolName_SetImplementationValue(global::LightSwitchApplication.frequencyView.DetailsClass d, string v)
                {
                    d.ImplementationEntity.SchoolName = v;
                }
                private static void _SchoolName_OnValueChanged(global::LightSwitchApplication.frequencyView e)
                {
                    e.SchoolName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, int>.Entry
                    frequencyNum = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, int>.Entry(
                        "frequencyNum",
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._frequencyNum_Stub,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._frequencyNum_ComputeIsReadOnly,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._frequencyNum_Validate,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._frequencyNum_GetImplementationValue,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._frequencyNum_SetImplementationValue,
                        global::LightSwitchApplication.frequencyView.DetailsClass.PropertySetProperties._frequencyNum_OnValueChanged);
                private static void _frequencyNum_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.frequencyView.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, int>.Data> c, global::LightSwitchApplication.frequencyView.DetailsClass d, object sf)
                {
                    c(d, ref d._frequencyNum, sf);
                }
                private static bool _frequencyNum_ComputeIsReadOnly(global::LightSwitchApplication.frequencyView e)
                {
                    bool result = false;
                    e.frequencyNum_IsReadOnly(ref result);
                    return result;
                }
                private static void _frequencyNum_Validate(global::LightSwitchApplication.frequencyView e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.frequencyNum_Validate(r);
                }
                private static int _frequencyNum_GetImplementationValue(global::LightSwitchApplication.frequencyView.DetailsClass d)
                {
                    return d.ImplementationEntity.frequencyNum;
                }
                private static void _frequencyNum_SetImplementationValue(global::LightSwitchApplication.frequencyView.DetailsClass d, int v)
                {
                    d.ImplementationEntity.frequencyNum = v;
                }
                private static void _frequencyNum_OnValueChanged(global::LightSwitchApplication.frequencyView e)
                {
                    e.frequencyNum_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, string>.Data _SchoolName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.frequencyView, global::LightSwitchApplication.frequencyView.DetailsClass, int>.Data _frequencyNum;
            
        }
    
        #endregion
    }
    
    #endregion
}
