

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class ActivityType : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the ActivityType entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ActivityType()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ActivityType(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ActivityType> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.ActivityType.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActivityType_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ActivityType_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.ActivityType.DetailsClass.SetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string T
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.T);
            }
            set
            {
                global::LightSwitchApplication.ActivityType.DetailsClass.SetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.T, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void T_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void T_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void T_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.ActivityType.DetailsClass.SetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Activity> Activity
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Activity);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Activity> ActivityQuery
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetQuery(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Activity);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TopicCollection> TopicCollections
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetValue(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.TopicCollections);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TopicCollection> TopicCollectionsQuery
        {
            get
            {
                return global::LightSwitchApplication.ActivityType.DetailsClass.GetQuery(this, global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.TopicCollections);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.ActivityType,
                global::LightSwitchApplication.ActivityType.DetailsClass,
                global::LightSwitchApplication.ActivityType.DetailsClass.IImplementation,
                global::LightSwitchApplication.ActivityType.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass>.Entry
                __ActivityTypeEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass>.Entry(
                    global::LightSwitchApplication.ActivityType.DetailsClass.__ActivityType_CreateNew,
                    global::LightSwitchApplication.ActivityType.DetailsClass.__ActivityType_Created,
                    global::LightSwitchApplication.ActivityType.DetailsClass.__ActivityType_AllowSaveWithErrors);
            private static global::LightSwitchApplication.ActivityType __ActivityType_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.ActivityType> es)
            {
                return new global::LightSwitchApplication.ActivityType(es);
            }
            private static void __ActivityType_Created(global::LightSwitchApplication.ActivityType e)
            {
                e.ActivityType_Created();
            }
            private static bool __ActivityType_AllowSaveWithErrors(global::LightSwitchApplication.ActivityType e)
            {
                bool result = false;
                e.ActivityType_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.ActivityType.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, string> T
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.T) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.Activity> Activity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Activity) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.Activity>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.TopicCollection> TopicCollections
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.TopicCollections) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.TopicCollection>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string T { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Activity { get; }
                new global::System.Collections.IEnumerable TopicCollections { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActivityType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, int>.Data> c, global::LightSwitchApplication.ActivityType.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.ActivityType e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.ActivityType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.ActivityType.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.ActivityType e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, string>.Entry
                    T = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, string>.Entry(
                        "T",
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._T_Stub,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._T_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._T_Validate,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._T_GetImplementationValue,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._T_SetImplementationValue,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._T_OnValueChanged);
                private static void _T_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActivityType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, string>.Data> c, global::LightSwitchApplication.ActivityType.DetailsClass d, object sf)
                {
                    c(d, ref d._T, sf);
                }
                private static bool _T_ComputeIsReadOnly(global::LightSwitchApplication.ActivityType e)
                {
                    bool result = false;
                    e.T_IsReadOnly(ref result);
                    return result;
                }
                private static void _T_Validate(global::LightSwitchApplication.ActivityType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.T_Validate(r);
                }
                private static string _T_GetImplementationValue(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.ImplementationEntity.T;
                }
                private static void _T_SetImplementationValue(global::LightSwitchApplication.ActivityType.DetailsClass d, string v)
                {
                    d.ImplementationEntity.T = v;
                }
                private static void _T_OnValueChanged(global::LightSwitchApplication.ActivityType e)
                {
                    e.T_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActivityType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.ActivityType.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.ActivityType e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.ActivityType e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.ActivityType.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.ActivityType e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.Activity>.Entry
                    Activity = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.Activity>.Entry(
                        "Activity",
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Activity_Stub,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Activity_GetReferencedEntities,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._Activity_GetEntityCollection);
                private static void _Activity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActivityType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.Activity>.Data> c, global::LightSwitchApplication.ActivityType.DetailsClass d, object sf)
                {
                    c(d, ref d._Activity, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Activity> _Activity_GetReferencedEntities(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Activity, global::LightSwitchApplication.Activity.DetailsClass>(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.Activity, ref d._Activity);
                }
                private static global::System.Collections.IEnumerable _Activity_GetEntityCollection(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.ImplementationEntity.Activity;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.TopicCollection>.Entry
                    TopicCollections = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.TopicCollection>.Entry(
                        "TopicCollections",
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._TopicCollections_Stub,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._TopicCollections_GetReferencedEntities,
                        global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties._TopicCollections_GetEntityCollection);
                private static void _TopicCollections_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.ActivityType.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.TopicCollection>.Data> c, global::LightSwitchApplication.ActivityType.DetailsClass d, object sf)
                {
                    c(d, ref d._TopicCollections, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TopicCollection> _TopicCollections_GetReferencedEntities(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TopicCollection, global::LightSwitchApplication.TopicCollection.DetailsClass>(global::LightSwitchApplication.ActivityType.DetailsClass.PropertySetProperties.TopicCollections, ref d._TopicCollections);
                }
                private static global::System.Collections.IEnumerable _TopicCollections_GetEntityCollection(global::LightSwitchApplication.ActivityType.DetailsClass d)
                {
                    return d.ImplementationEntity.TopicCollections;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, string>.Data _T;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.Activity>.Data _Activity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.ActivityType, global::LightSwitchApplication.ActivityType.DetailsClass, global::LightSwitchApplication.TopicCollection>.Data _TopicCollections;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class School : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the School entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public School()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public School(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.School> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.School.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void School_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void School_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.School.DetailsClass.SetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Titel
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Titel);
            }
            set
            {
                global::LightSwitchApplication.School.DetailsClass.SetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Titel, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Titel_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Titel_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Titel_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.School.DetailsClass.SetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.SchoolPart> SchoolParts
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.SchoolParts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SchoolPart> SchoolPartsQuery
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetQuery(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.SchoolParts);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PartnerSchools> PartnerSchools
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetValue(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.PartnerSchools);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PartnerSchools> PartnerSchoolsQuery
        {
            get
            {
                return global::LightSwitchApplication.School.DetailsClass.GetQuery(this, global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.PartnerSchools);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.School,
                global::LightSwitchApplication.School.DetailsClass,
                global::LightSwitchApplication.School.DetailsClass.IImplementation,
                global::LightSwitchApplication.School.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass>.Entry
                __SchoolEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass>.Entry(
                    global::LightSwitchApplication.School.DetailsClass.__School_CreateNew,
                    global::LightSwitchApplication.School.DetailsClass.__School_Created,
                    global::LightSwitchApplication.School.DetailsClass.__School_AllowSaveWithErrors);
            private static global::LightSwitchApplication.School __School_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.School> es)
            {
                return new global::LightSwitchApplication.School(es);
            }
            private static void __School_Created(global::LightSwitchApplication.School e)
            {
                e.School_Created();
            }
            private static bool __School_AllowSaveWithErrors(global::LightSwitchApplication.School e)
            {
                bool result = false;
                e.School_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.School.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, string> Titel
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.Titel) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.SchoolPart> SchoolParts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.SchoolParts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.SchoolPart>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.PartnerSchools> PartnerSchools
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.PartnerSchools) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.PartnerSchools>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Titel { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable SchoolParts { get; }
                new global::System.Collections.IEnumerable PartnerSchools { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.School.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, int>.Data> c, global::LightSwitchApplication.School.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.School e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.School e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.School.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.School e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, string>.Entry
                    Titel = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, string>.Entry(
                        "Titel",
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Titel_Stub,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Titel_ComputeIsReadOnly,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Titel_Validate,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Titel_GetImplementationValue,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Titel_SetImplementationValue,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._Titel_OnValueChanged);
                private static void _Titel_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.School.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, string>.Data> c, global::LightSwitchApplication.School.DetailsClass d, object sf)
                {
                    c(d, ref d._Titel, sf);
                }
                private static bool _Titel_ComputeIsReadOnly(global::LightSwitchApplication.School e)
                {
                    bool result = false;
                    e.Titel_IsReadOnly(ref result);
                    return result;
                }
                private static void _Titel_Validate(global::LightSwitchApplication.School e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Titel_Validate(r);
                }
                private static string _Titel_GetImplementationValue(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.ImplementationEntity.Titel;
                }
                private static void _Titel_SetImplementationValue(global::LightSwitchApplication.School.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Titel = v;
                }
                private static void _Titel_OnValueChanged(global::LightSwitchApplication.School e)
                {
                    e.Titel_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.School.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.School.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.School e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.School e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.School.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.School e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.SchoolPart>.Entry
                    SchoolParts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.SchoolPart>.Entry(
                        "SchoolParts",
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._SchoolParts_Stub,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._SchoolParts_GetReferencedEntities,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._SchoolParts_GetEntityCollection);
                private static void _SchoolParts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.School.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.SchoolPart>.Data> c, global::LightSwitchApplication.School.DetailsClass d, object sf)
                {
                    c(d, ref d._SchoolParts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SchoolPart> _SchoolParts_GetReferencedEntities(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.SchoolPart, global::LightSwitchApplication.SchoolPart.DetailsClass>(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.SchoolParts, ref d._SchoolParts);
                }
                private static global::System.Collections.IEnumerable _SchoolParts_GetEntityCollection(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.ImplementationEntity.SchoolParts;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.PartnerSchools>.Entry
                    PartnerSchools = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.PartnerSchools>.Entry(
                        "PartnerSchools",
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._PartnerSchools_Stub,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._PartnerSchools_GetReferencedEntities,
                        global::LightSwitchApplication.School.DetailsClass.PropertySetProperties._PartnerSchools_GetEntityCollection);
                private static void _PartnerSchools_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.School.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.PartnerSchools>.Data> c, global::LightSwitchApplication.School.DetailsClass d, object sf)
                {
                    c(d, ref d._PartnerSchools, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PartnerSchools> _PartnerSchools_GetReferencedEntities(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PartnerSchools, global::LightSwitchApplication.PartnerSchools.DetailsClass>(global::LightSwitchApplication.School.DetailsClass.PropertySetProperties.PartnerSchools, ref d._PartnerSchools);
                }
                private static global::System.Collections.IEnumerable _PartnerSchools_GetEntityCollection(global::LightSwitchApplication.School.DetailsClass d)
                {
                    return d.ImplementationEntity.PartnerSchools;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, string>.Data _Titel;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.SchoolPart>.Data _SchoolParts;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.School, global::LightSwitchApplication.School.DetailsClass, global::LightSwitchApplication.PartnerSchools>.Data _PartnerSchools;
            
        }
    
        #endregion
    }
    
    #endregion
}
