

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class PartnersGroups : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PartnersGroups entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PartnersGroups()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PartnersGroups(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PartnersGroups> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PartnersGroups.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PartnersGroups_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PartnersGroups_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.PartnersGroups.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.PartnersGroups.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MoreDetails
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.MoreDetails);
            }
            set
            {
                global::LightSwitchApplication.PartnersGroups.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.MoreDetails, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoreDetails_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoreDetails_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoreDetails_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.PartnersGroups.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Partners> Partner
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Partner);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Partners> PartnerQuery
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetQuery(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Partner);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.PartnersReport> PartnersReport
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.PartnersReport);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.PartnersReport> PartnersReportQuery
        {
            get
            {
                return global::LightSwitchApplication.PartnersGroups.DetailsClass.GetQuery(this, global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.PartnersReport);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PartnersGroups,
                global::LightSwitchApplication.PartnersGroups.DetailsClass,
                global::LightSwitchApplication.PartnersGroups.DetailsClass.IImplementation,
                global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass>.Entry
                __PartnersGroupsEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass>.Entry(
                    global::LightSwitchApplication.PartnersGroups.DetailsClass.__PartnersGroups_CreateNew,
                    global::LightSwitchApplication.PartnersGroups.DetailsClass.__PartnersGroups_Created,
                    global::LightSwitchApplication.PartnersGroups.DetailsClass.__PartnersGroups_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PartnersGroups __PartnersGroups_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PartnersGroups> es)
            {
                return new global::LightSwitchApplication.PartnersGroups(es);
            }
            private static void __PartnersGroups_Created(global::LightSwitchApplication.PartnersGroups e)
            {
                e.PartnersGroups_Created();
            }
            private static bool __PartnersGroups_AllowSaveWithErrors(global::LightSwitchApplication.PartnersGroups e)
            {
                bool result = false;
                e.PartnersGroups_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string> MoreDetails
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.MoreDetails) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.Partners> Partner
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Partner) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.Partners>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.PartnersReport> PartnersReport
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.PartnersReport) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.PartnersReport>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new string MoreDetails { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable Partner { get; }
                new global::System.Collections.IEnumerable PartnersReport { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnersGroups.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, int>.Data> c, global::LightSwitchApplication.PartnersGroups.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.PartnersGroups e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.PartnersGroups e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.PartnersGroups e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnersGroups.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Data> c, global::LightSwitchApplication.PartnersGroups.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.PartnersGroups e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.PartnersGroups e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.PartnersGroups e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Entry
                    MoreDetails = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Entry(
                        "MoreDetails",
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._MoreDetails_Stub,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._MoreDetails_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._MoreDetails_Validate,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._MoreDetails_GetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._MoreDetails_SetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._MoreDetails_OnValueChanged);
                private static void _MoreDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnersGroups.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Data> c, global::LightSwitchApplication.PartnersGroups.DetailsClass d, object sf)
                {
                    c(d, ref d._MoreDetails, sf);
                }
                private static bool _MoreDetails_ComputeIsReadOnly(global::LightSwitchApplication.PartnersGroups e)
                {
                    bool result = false;
                    e.MoreDetails_IsReadOnly(ref result);
                    return result;
                }
                private static void _MoreDetails_Validate(global::LightSwitchApplication.PartnersGroups e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MoreDetails_Validate(r);
                }
                private static string _MoreDetails_GetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.ImplementationEntity.MoreDetails;
                }
                private static void _MoreDetails_SetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MoreDetails = v;
                }
                private static void _MoreDetails_OnValueChanged(global::LightSwitchApplication.PartnersGroups e)
                {
                    e.MoreDetails_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnersGroups.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.PartnersGroups.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.PartnersGroups e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.PartnersGroups e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.PartnersGroups.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.PartnersGroups e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.Partners>.Entry
                    Partner = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.Partners>.Entry(
                        "Partner",
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Partner_Stub,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Partner_GetReferencedEntities,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._Partner_GetEntityCollection);
                private static void _Partner_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnersGroups.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.Partners>.Data> c, global::LightSwitchApplication.PartnersGroups.DetailsClass d, object sf)
                {
                    c(d, ref d._Partner, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Partners> _Partner_GetReferencedEntities(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Partners, global::LightSwitchApplication.Partners.DetailsClass>(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.Partner, ref d._Partner);
                }
                private static global::System.Collections.IEnumerable _Partner_GetEntityCollection(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.ImplementationEntity.Partner;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.PartnersReport>.Entry
                    PartnersReport = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.PartnersReport>.Entry(
                        "PartnersReport",
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._PartnersReport_Stub,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._PartnersReport_GetReferencedEntities,
                        global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties._PartnersReport_GetEntityCollection);
                private static void _PartnersReport_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnersGroups.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.PartnersReport>.Data> c, global::LightSwitchApplication.PartnersGroups.DetailsClass d, object sf)
                {
                    c(d, ref d._PartnersReport, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.PartnersReport> _PartnersReport_GetReferencedEntities(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.PartnersReport, global::LightSwitchApplication.PartnersReport.DetailsClass>(global::LightSwitchApplication.PartnersGroups.DetailsClass.PropertySetProperties.PartnersReport, ref d._PartnersReport);
                }
                private static global::System.Collections.IEnumerable _PartnersReport_GetEntityCollection(global::LightSwitchApplication.PartnersGroups.DetailsClass d)
                {
                    return d.ImplementationEntity.PartnersReport;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, string>.Data _MoreDetails;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.Partners>.Data _Partner;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnersGroups, global::LightSwitchApplication.PartnersGroups.DetailsClass, global::LightSwitchApplication.PartnersReport>.Data _PartnersReport;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class PartnerTypes : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the PartnerTypes entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PartnerTypes()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public PartnerTypes(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PartnerTypes> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.PartnerTypes.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PartnerTypes_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void PartnerTypes_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.PartnerTypes.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.PartnerTypes.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.PartnerTypes.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.PartnerTypes.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string MoreDetails
        {
            get
            {
                return global::LightSwitchApplication.PartnerTypes.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.MoreDetails);
            }
            set
            {
                global::LightSwitchApplication.PartnerTypes.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.MoreDetails, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoreDetails_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoreDetails_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void MoreDetails_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.PartnerTypes.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.PartnerTypes.DetailsClass.SetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Partners> PartnersCollection
        {
            get
            {
                return global::LightSwitchApplication.PartnerTypes.DetailsClass.GetValue(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.PartnersCollection);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Partners> PartnersCollectionQuery
        {
            get
            {
                return global::LightSwitchApplication.PartnerTypes.DetailsClass.GetQuery(this, global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.PartnersCollection);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.PartnerTypes,
                global::LightSwitchApplication.PartnerTypes.DetailsClass,
                global::LightSwitchApplication.PartnerTypes.DetailsClass.IImplementation,
                global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass>.Entry
                __PartnerTypesEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass>.Entry(
                    global::LightSwitchApplication.PartnerTypes.DetailsClass.__PartnerTypes_CreateNew,
                    global::LightSwitchApplication.PartnerTypes.DetailsClass.__PartnerTypes_Created,
                    global::LightSwitchApplication.PartnerTypes.DetailsClass.__PartnerTypes_AllowSaveWithErrors);
            private static global::LightSwitchApplication.PartnerTypes __PartnerTypes_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.PartnerTypes> es)
            {
                return new global::LightSwitchApplication.PartnerTypes(es);
            }
            private static void __PartnerTypes_Created(global::LightSwitchApplication.PartnerTypes e)
            {
                e.PartnerTypes_Created();
            }
            private static bool __PartnerTypes_AllowSaveWithErrors(global::LightSwitchApplication.PartnerTypes e)
            {
                bool result = false;
                e.PartnerTypes_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string> MoreDetails
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.MoreDetails) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, global::LightSwitchApplication.Partners> PartnersCollection
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.PartnersCollection) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, global::LightSwitchApplication.Partners>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new string MoreDetails { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable PartnersCollection { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnerTypes.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, int>.Data> c, global::LightSwitchApplication.PartnerTypes.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.PartnerTypes e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.PartnerTypes e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.PartnerTypes e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnerTypes.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Data> c, global::LightSwitchApplication.PartnerTypes.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.PartnerTypes e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.PartnerTypes e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.PartnerTypes e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Entry
                    MoreDetails = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Entry(
                        "MoreDetails",
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._MoreDetails_Stub,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._MoreDetails_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._MoreDetails_Validate,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._MoreDetails_GetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._MoreDetails_SetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._MoreDetails_OnValueChanged);
                private static void _MoreDetails_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnerTypes.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Data> c, global::LightSwitchApplication.PartnerTypes.DetailsClass d, object sf)
                {
                    c(d, ref d._MoreDetails, sf);
                }
                private static bool _MoreDetails_ComputeIsReadOnly(global::LightSwitchApplication.PartnerTypes e)
                {
                    bool result = false;
                    e.MoreDetails_IsReadOnly(ref result);
                    return result;
                }
                private static void _MoreDetails_Validate(global::LightSwitchApplication.PartnerTypes e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.MoreDetails_Validate(r);
                }
                private static string _MoreDetails_GetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d)
                {
                    return d.ImplementationEntity.MoreDetails;
                }
                private static void _MoreDetails_SetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d, string v)
                {
                    d.ImplementationEntity.MoreDetails = v;
                }
                private static void _MoreDetails_OnValueChanged(global::LightSwitchApplication.PartnerTypes e)
                {
                    e.MoreDetails_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnerTypes.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.PartnerTypes.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.PartnerTypes e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.PartnerTypes e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.PartnerTypes.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.PartnerTypes e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, global::LightSwitchApplication.Partners>.Entry
                    PartnersCollection = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, global::LightSwitchApplication.Partners>.Entry(
                        "PartnersCollection",
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._PartnersCollection_Stub,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._PartnersCollection_GetReferencedEntities,
                        global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties._PartnersCollection_GetEntityCollection);
                private static void _PartnersCollection_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.PartnerTypes.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, global::LightSwitchApplication.Partners>.Data> c, global::LightSwitchApplication.PartnerTypes.DetailsClass d, object sf)
                {
                    c(d, ref d._PartnersCollection, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Partners> _PartnersCollection_GetReferencedEntities(global::LightSwitchApplication.PartnerTypes.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Partners, global::LightSwitchApplication.Partners.DetailsClass>(global::LightSwitchApplication.PartnerTypes.DetailsClass.PropertySetProperties.PartnersCollection, ref d._PartnersCollection);
                }
                private static global::System.Collections.IEnumerable _PartnersCollection_GetEntityCollection(global::LightSwitchApplication.PartnerTypes.DetailsClass d)
                {
                    return d.ImplementationEntity.PartnersCollection;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, string>.Data _MoreDetails;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.PartnerTypes, global::LightSwitchApplication.PartnerTypes.DetailsClass, global::LightSwitchApplication.Partners>.Data _PartnersCollection;
            
        }
    
        #endregion
    }
    
    #endregion
}
