

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class City : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the City entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public City()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public City(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.City> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.City.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void City_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.City.DetailsClass.SetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.City.DetailsClass.SetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.City.DetailsClass.SetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.SchoolPart> SchoolParts
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.SchoolParts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SchoolPart> SchoolPartsQuery
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetQuery(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.SchoolParts);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Counselor> Counselors
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Counselors);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Counselor> CounselorsQuery
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetQuery(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Counselors);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.District DefaultDistrict
        {
            get
            {
                return global::LightSwitchApplication.City.DetailsClass.GetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.DefaultDistrict);
            }
            set
            {
                global::LightSwitchApplication.City.DetailsClass.SetValue(this, global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.DefaultDistrict, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DefaultDistrict_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DefaultDistrict_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DefaultDistrict_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.City,
                global::LightSwitchApplication.City.DetailsClass,
                global::LightSwitchApplication.City.DetailsClass.IImplementation,
                global::LightSwitchApplication.City.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>.Entry
                __CityEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>.Entry(
                    global::LightSwitchApplication.City.DetailsClass.__City_CreateNew,
                    global::LightSwitchApplication.City.DetailsClass.__City_Created,
                    global::LightSwitchApplication.City.DetailsClass.__City_AllowSaveWithErrors);
            private static global::LightSwitchApplication.City __City_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.City> es)
            {
                return new global::LightSwitchApplication.City(es);
            }
            private static void __City_Created(global::LightSwitchApplication.City e)
            {
                e.City_Created();
            }
            private static bool __City_AllowSaveWithErrors(global::LightSwitchApplication.City e)
            {
                bool result = false;
                e.City_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.City.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.SchoolPart> SchoolParts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.SchoolParts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.SchoolPart>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.Counselor> Counselors
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Counselors) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.Counselor>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.District> DefaultDistrict
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.DefaultDistrict) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.District>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable SchoolParts { get; }
                new global::System.Collections.IEnumerable Counselors { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation DefaultDistrict { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.City.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, int>.Data> c, global::LightSwitchApplication.City.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.City e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.City e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.City.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.City e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.City.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, string>.Data> c, global::LightSwitchApplication.City.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.City e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.City e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.City.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.City e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.City.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.City.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.City e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.City e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.City.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.City e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.SchoolPart>.Entry
                    SchoolParts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.SchoolPart>.Entry(
                        "SchoolParts",
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._SchoolParts_Stub,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._SchoolParts_GetReferencedEntities,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._SchoolParts_GetEntityCollection);
                private static void _SchoolParts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.City.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.SchoolPart>.Data> c, global::LightSwitchApplication.City.DetailsClass d, object sf)
                {
                    c(d, ref d._SchoolParts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SchoolPart> _SchoolParts_GetReferencedEntities(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.SchoolPart, global::LightSwitchApplication.SchoolPart.DetailsClass>(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.SchoolParts, ref d._SchoolParts);
                }
                private static global::System.Collections.IEnumerable _SchoolParts_GetEntityCollection(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.ImplementationEntity.SchoolParts;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.Counselor>.Entry
                    Counselors = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.Counselor>.Entry(
                        "Counselors",
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Counselors_Stub,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Counselors_GetReferencedEntities,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._Counselors_GetEntityCollection);
                private static void _Counselors_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.City.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.Counselor>.Data> c, global::LightSwitchApplication.City.DetailsClass d, object sf)
                {
                    c(d, ref d._Counselors, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Counselor> _Counselors_GetReferencedEntities(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Counselor, global::LightSwitchApplication.Counselor.DetailsClass>(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.Counselors, ref d._Counselors);
                }
                private static global::System.Collections.IEnumerable _Counselors_GetEntityCollection(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.ImplementationEntity.Counselors;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.District>.Entry
                    DefaultDistrict = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.District>.Entry(
                        "DefaultDistrict",
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_Stub,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_ComputeIsReadOnly,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_Validate,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_GetCoreImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_GetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_SetImplementationValue,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_Refresh,
                        global::LightSwitchApplication.City.DetailsClass.PropertySetProperties._DefaultDistrict_OnValueChanged);
                private static void _DefaultDistrict_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.City.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.District>.Data> c, global::LightSwitchApplication.City.DetailsClass d, object sf)
                {
                    c(d, ref d._DefaultDistrict, sf);
                }
                private static bool _DefaultDistrict_ComputeIsReadOnly(global::LightSwitchApplication.City e)
                {
                    bool result = false;
                    e.DefaultDistrict_IsReadOnly(ref result);
                    return result;
                }
                private static void _DefaultDistrict_Validate(global::LightSwitchApplication.City e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DefaultDistrict_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _DefaultDistrict_GetCoreImplementationValue(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.ImplementationEntity.DefaultDistrict;
                }
                private static global::LightSwitchApplication.District _DefaultDistrict_GetImplementationValue(global::LightSwitchApplication.City.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.DefaultDistrict, ref d._DefaultDistrict);
                }
                private static void _DefaultDistrict_SetImplementationValue(global::LightSwitchApplication.City.DetailsClass d, global::LightSwitchApplication.District v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.DefaultDistrict, ref d._DefaultDistrict, (i, ev) => i.DefaultDistrict = ev, v);
                }
                private static void _DefaultDistrict_Refresh(global::LightSwitchApplication.City.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.City.DetailsClass.PropertySetProperties.DefaultDistrict, ref d._DefaultDistrict);
                }
                private static void _DefaultDistrict_OnValueChanged(global::LightSwitchApplication.City e)
                {
                    e.DefaultDistrict_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.SchoolPart>.Data _SchoolParts;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.Counselor>.Data _Counselors;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass, global::LightSwitchApplication.District>.Data _DefaultDistrict;
            
        }
    
        #endregion
    }
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
    public sealed partial class District : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the District entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public District()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public District(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.District> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.District.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void District_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void District_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.District.DetailsClass.SetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.District.DetailsClass.SetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.District.DetailsClass.SetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.SchoolPart> SchoolParts
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.SchoolParts);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.SchoolPart> SchoolPartsQuery
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetQuery(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.SchoolParts);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.City> Cities
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Cities);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.City> CitiesQuery
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetQuery(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Cities);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Counselor> Counselors
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Counselors);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Counselor> CounselorsQuery
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetQuery(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Counselors);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Activity> Activities
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetValue(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Activities);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Activity> ActivitiesQuery
        {
            get
            {
                return global::LightSwitchApplication.District.DetailsClass.GetQuery(this, global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Activities);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.District,
                global::LightSwitchApplication.District.DetailsClass,
                global::LightSwitchApplication.District.DetailsClass.IImplementation,
                global::LightSwitchApplication.District.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>.Entry
                __DistrictEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>.Entry(
                    global::LightSwitchApplication.District.DetailsClass.__District_CreateNew,
                    global::LightSwitchApplication.District.DetailsClass.__District_Created,
                    global::LightSwitchApplication.District.DetailsClass.__District_AllowSaveWithErrors);
            private static global::LightSwitchApplication.District __District_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.District> es)
            {
                return new global::LightSwitchApplication.District(es);
            }
            private static void __District_Created(global::LightSwitchApplication.District e)
            {
                e.District_Created();
            }
            private static bool __District_AllowSaveWithErrors(global::LightSwitchApplication.District e)
            {
                bool result = false;
                e.District_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.District.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.SchoolPart> SchoolParts
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.SchoolParts) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.SchoolPart>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.City> Cities
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Cities) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.City>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Counselor> Counselors
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Counselors) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Counselor>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Activity> Activities
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Activities) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Activity>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new string Title { get; set; }
                new byte[] RowVersion { get; set; }
                new global::System.Collections.IEnumerable SchoolParts { get; }
                new global::System.Collections.IEnumerable Cities { get; }
                new global::System.Collections.IEnumerable Counselors { get; }
                new global::System.Collections.IEnumerable Activities { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, int>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.District e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.District e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.District.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.District e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, string>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.District e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.District e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.District.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.District e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.District e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.District e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.District.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.District e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.SchoolPart>.Entry
                    SchoolParts = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.SchoolPart>.Entry(
                        "SchoolParts",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._SchoolParts_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._SchoolParts_GetReferencedEntities,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._SchoolParts_GetEntityCollection);
                private static void _SchoolParts_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.SchoolPart>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._SchoolParts, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.SchoolPart> _SchoolParts_GetReferencedEntities(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.SchoolPart, global::LightSwitchApplication.SchoolPart.DetailsClass>(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.SchoolParts, ref d._SchoolParts);
                }
                private static global::System.Collections.IEnumerable _SchoolParts_GetEntityCollection(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.SchoolParts;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.City>.Entry
                    Cities = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.City>.Entry(
                        "Cities",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Cities_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Cities_GetReferencedEntities,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Cities_GetEntityCollection);
                private static void _Cities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.City>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._Cities, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.City> _Cities_GetReferencedEntities(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.City, global::LightSwitchApplication.City.DetailsClass>(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Cities, ref d._Cities);
                }
                private static global::System.Collections.IEnumerable _Cities_GetEntityCollection(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.Cities;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Counselor>.Entry
                    Counselors = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Counselor>.Entry(
                        "Counselors",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Counselors_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Counselors_GetReferencedEntities,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Counselors_GetEntityCollection);
                private static void _Counselors_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Counselor>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._Counselors, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Counselor> _Counselors_GetReferencedEntities(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Counselor, global::LightSwitchApplication.Counselor.DetailsClass>(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Counselors, ref d._Counselors);
                }
                private static global::System.Collections.IEnumerable _Counselors_GetEntityCollection(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.Counselors;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Activity>.Entry
                    Activities = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Activity>.Entry(
                        "Activities",
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Activities_Stub,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Activities_GetReferencedEntities,
                        global::LightSwitchApplication.District.DetailsClass.PropertySetProperties._Activities_GetEntityCollection);
                private static void _Activities_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.District.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Activity>.Data> c, global::LightSwitchApplication.District.DetailsClass d, object sf)
                {
                    c(d, ref d._Activities, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Activity> _Activities_GetReferencedEntities(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Activity, global::LightSwitchApplication.Activity.DetailsClass>(global::LightSwitchApplication.District.DetailsClass.PropertySetProperties.Activities, ref d._Activities);
                }
                private static global::System.Collections.IEnumerable _Activities_GetEntityCollection(global::LightSwitchApplication.District.DetailsClass d)
                {
                    return d.ImplementationEntity.Activities;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.SchoolPart>.Data _SchoolParts;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.City>.Data _Cities;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Counselor>.Data _Counselors;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.District, global::LightSwitchApplication.District.DetailsClass, global::LightSwitchApplication.Activity>.Data _Activities;
            
        }
    
        #endregion
    }
    
    #endregion
}
